version: "3.9"

services:
  tuyul_reflective_core:
    build:
      context: .
      dockerfile: dockerfile
    container_name: tuyul_fx_core
    restart: always
    environment:
      - MODE=reflective
      - VERSION=5.7.8
      - BRIDGE=RBP_v2.2
    volumes:
      - ./repos:/app/repos
      - ./logs:/app/logs
    command: ["python", "main.py"]

  tuyul_reflective_dashboard:
    image: streamlit:latest
    container_name: tuyul_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./repos:/app/repos
      - ./tests:/app/tests
    command: ["streamlit", "run", "reflective_test_dashboard.py"]
