from setuptools import setup, find_packages

setup(
    name="tuyul-fx-hybrid",
    version="5.4.0",
    description="TUYUL-FX-HYBRID AGI Orchestrator with Fusion, Reflex, and Risk layers",
    author="TUYUL KARTEL",
    author_email="info@tuyul-kartel.ai",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.9",
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn[standard]>=0.24.0",
        "pydantic>=2.5.0",
        "pydantic-settings>=2.1.0",
        "httpx>=0.25.1",
        "openai>=1.3.5",
        "python-multipart>=0.0.6",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-dotenv>=1.0.0",
        "aiofiles>=23.2.1",
        "pytesseract>=0.3.10",
        "Pillow>=10.1.0",
        "numpy>=1.26.2",
        "pandas>=2.1.3",
        "scikit-learn>=1.3.2",
        "torch>=2.1.1",
        "transformers>=4.35.2",
        "PyGithub>=2.1.1",
        "gitpython>=3.1.40",
        "redis>=5.0.1",
        "celery>=5.3.4",
        "sqlalchemy>=2.0.23",
        "alembic>=1.12.1",
        "psycopg2-binary>=2.9.9",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.3",
            "pytest-asyncio>=0.21.1",
            "pytest-cov>=4.1.0",
            "black>=23.11.0",
            "flake8>=6.1.0",
            "mypy>=1.7.1",
        ]
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
