# Prompt Profiles
profiles:
  reflective:
    meta_prompt: chat_reflective/prompt_templates/meta_prompt.txt
    reasoning_prompt: chat_reflective/prompt_templates/reasoning_prompt.txt
    reflective_prompt: chat_reflective/prompt_templates/reflective_prompt.txt
